# Homework 09

## Group 10

In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
# The task
from random import randint, sample

# Simple yield generator
def simple_gen(num_to_gen):
    num = 0
    while num < num_to_gen:
        yield randint(0,9)
        num += 1

print([x for x in simple_gen(10)])

[7, 9, 8, 5, 9, 1, 5, 1, 4, 4]


In [6]:
# The Tensorflow version

# Creating a generator allows to control the values via the seed
rng = tf.random.Generator.from_seed(1)

def generate_sequence(nums, gen=rng):
    """generates a tf.Dataset of a given length with random numbers provided by a generator"""
    return tf.data.Dataset.from_tensor_slices(gen.uniform(shape=(1, nums), maxval=10, dtype=tf.int32))


# Needs a way to discribe the output shape, not sure how to implement this yet
def generate_sequence2(nums):
    """generates a tf.Dataset of a given length with random numbers provided by a generator"""
    return tf.data.Dataset.from_generator(simple_gen, args=[nums], output_types=tf.int32)

ds = generate_sequence(100)
ds2 = generate_sequence2(100)
ds.element_spec, ds2.element_spec



(TensorSpec(shape=(100,), dtype=tf.int32, name=None),
 TensorSpec(shape=<unknown>, dtype=tf.int32, name=None))

In [4]:
# Generate the context:
np.random.choice(a=10, size=2, replace=False)

context = tf.random.uniform(shape=(2,), maxval=10, dtype=tf.int32)
context.numpy()


array([9, 2], dtype=int32)

In [7]:
def generate_data(batch_size):
    # Generate two random digits as context
    context = sample(range(0,10), 2)

    # Generate the number sequence with a length of batch size
    sequence = generate_sequence2(batch_size)

    # Count the occurances of the context in the generated sequence
    for t in sequence:
        targ1 = tf.math.count_nonzero(tf.equal(t, context[0]))
        targ2 = tf.math.count_nonzero(tf.equal(t, context[1]))
    target = [targ1, targ2]

    return tf.constant(context), sequence, target

generate_data(20)


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 9], dtype=int32)>,
 <FlatMapDataset shapes: <unknown>, types: tf.int32>,
 [<tf.Tensor: shape=(), dtype=int64, numpy=0>,
  <tf.Tensor: shape=(), dtype=int64, numpy=0>])